src/Http/Controllers/TeamController.php, src/WinkAuthor.php
=> Gravatar over random profile images

public/app.js, public/mix-manifest.json, resources/js/screens/posts/edit.vue
Default title as `Draft`
Default slug as `draft-{uuid}`
if the post contains the default title or the default slug, it doesn't allow publishing it.
Asked here https://github.com/writingink/wink/issues/4#issuecomment-436954430
=> Prevent publishing a post if it contains default title or default slug

readme.md
This PR is to fix typos in readme.md
=> Fix typos in readme file

src/Migrations/2018_10_30_000000_create_tables.php
=> UUID type for author_id

public/app.js, public/mix-manifest.json, resources/js/screens/team/edit.vue
Fix a typo in the title of the New Author page
=> New Author Page Typo fix

public/app.js, public/mix-manifest.json, resources/js/screens/pages/edit.vue
Change the button of New Page modal from "Cancel" to "Done" and make it Primary.
=> Change New Page modal button

.editorconfig, .gitattributes
=> Add and .editorconfig file.

src/Http/Controllers/PagesController.php, src/Http/Controllers/PostsController.php, src/Http/Controllers/TagsController.php, src/Http/Controllers/TeamController.php, src/Http/Middleware/Authenticate.php, src/WinkPost.php
=> Fix various docblocks

src/Http/Controllers/PagesController.php, src/Http/Controllers/PostsController.php, src/Http/Controllers/TagsController.php, src/Http/Controllers/TeamController.php
=> Prefer stricter comparisons.

src/Console/MigrateCommand.php, src/Http/Controllers/ForgotPasswordController.php, src/Http/Controllers/TeamController.php
Directly call `Str` class methods.
=> Directly call Str class methods.

src/Console/MigrateCommand.php, src/Http/Controllers/ForgotPasswordController.php, src/Http/Controllers/TeamController.php
=> Add missing imports.

.styleci.yml
=> Enable StyleCI.

resources/views/layout.blade.php, src/Http/Controllers/SPAViewController.php
Extract some logic from the layout.
=> Extract some logic from the layout.

src/AbstractWinkModel.php, src/WinkAuthor.php, src/WinkPage.php, src/WinkPost.php, src/WinkTag.php
=> Create an abstract WinkModel.

src/Http/Controllers/ForgotPasswordController.php, src/Http/Controllers/ImageUploadsController.php, src/Http/Controllers/PagesController.php, src/Http/Controllers/PostsController.php, src/Http/Controllers/SPAViewController.php, src/Http/Controllers/TagsController.php, src/Http/Controllers/TeamController.php, src/Http/Middleware/Authenticate.php, src/Http/routes.php, src/Mail/ResetPasswordEmail.php, src/WinkAuthor.php, src/WinkPost.php, src/WinkTag.php
=> Enforce Laravel coding style.

composer.json, phpstan.neon.dist
Install phpstan as a dev dependency.
=> Install phpstan as a dev dependency.

src/WinkAuthor.php
The added hidden fields are password and remember_token
=> Add hidden fields to WinkAuthor model

readme.md
Mark the Search feature as completed in readme.md Road map.
=> Update readme.md Road map

resources/views/layout.blade.php, resources/views/login.blade.php, resources/views/request-password-reset.blade.php, resources/views/reset-password.blade.php
No need to resolve Google fonts twice.
=> No need to resolve Google fonts twice.

public/app.js, public/mix-manifest.json, resources/js/screens/loadsEntries.js
Correct the DocBlock for watchFiltersChanges function in loadEntries.js
=> Correct the DocBlock for watchFiltersChanges()

public/app.js, public/mix-manifest.json, resources/js/screens/posts/index.vue
Add Clear button to the filters Dropdown, which resets the filters and close the Dropdown.
=> Implement Clear filters feature

readme.md
Adds documentation on how to activate the unsplash integration
=> document unsplash integration

public/app.js, public/mix-manifest.json, resources/js/screens/posts/index.vue
I think the Select lists of Filters Dropdown need some styling, So I make this PR.
Screenshots from Firefox:
=> Style Select lists of Filters Dropdown

src/Http/Controllers/ForgotPasswordController.php, src/Http/Controllers/LoginController.php, src/Http/Controllers/PagesController.php, src/Http/Controllers/PostsController.php, src/Http/Controllers/TagsController.php, src/Http/Controllers/TeamController.php, src/Http/Resources/PagesResource.php, src/Http/Resources/PostsResource.php, src/Http/Resources/TagsResource.php, src/Http/Resources/TeamResource.php, src/WinkPost.php
=> Fix some docblocks.

readme.md
=> Some Readme adujustments

readme.md
Add Table of Contents to readme
=> Add Table of Contents to readme

resources/js/components/Alert.vue, resources/js/components/CropperModal.vue, resources/js/components/DateTimePicker.vue, resources/js/components/DropDown.vue, resources/js/components/Editor.vue, resources/js/components/FormErrors.vue, resources/js/components/FullscreenModal.vue, resources/js/components/ImagePicker.vue, resources/js/components/MiniEditor.vue, resources/js/components/Modal.vue, resources/js/components/MultiSelect.vue, resources/js/components/Notification.vue, resources/js/components/PageHeader.vue, resources/js/components/SEOModal.vue, resources/js/components/editorComponents/HTMLEmbedder.vue, resources/js/components/editorComponents/ImageUploader.vue, resources/js/partials/FilterDropdown.vue, resources/js/partials/Preloader.vue, resources/js/screens/404.vue, resources/js/screens/pages/edit.vue, resources/js/screens/pages/index.vue, resources/js/screens/posts/FeaturedImageUploader.vue, resources/js/screens/posts/edit.vue, resources/js/screens/posts/index.vue, resources/js/screens/tags/edit.vue, resources/js/screens/tags/index.vue, resources/js/screens/team/edit.vue, resources/js/screens/team/index.vue
The value "text/ecmascript-6" was breaking sublime syntax highlighting inside all vue component script tags.
=> Change script tag attrib. value to just "text/ecmascript".

readme.md
Just clarifying the documentation for how to activate the unsplash integration.
=> Update the documentation for unsplash

CONTRIBUTING.md, src/WinkAuthor.php
Two quick fixes:
**CONTRIBUTING.md**
- "compile de assets" -> "compile the assets"
**WinkAuthor.php**
- "Get the authors's avatar" -> "Get the author's avatar"
=> Minor spelling fixes in CONTRIBUTING / WinkAuthor

config/wink.php
- Updated Comment about middleware group
- Add new line in keeping with the rest
=> Config Documentation

composer.json
Adds L7 to supported versions.
=> support Laravel 7

readme.md
hi, thought for real beginners it would be comfortable to have a little more documentation on how to start with wInk. I've added some simple examples, so a beginner could at least setup a small blog with menu, and just care about the templates. Maybe this could help?
=> improved examples in documentation

src/Http/Controllers/TagsController.php
=> Paginate return

composer.json
Allow PHP 7.4
I did read the code and didn't find any place that shouldn't work. Please tag me if you find anything and I will take a look.
=> Allow PHP 7.4
