config/wink.php, src/WinkServiceProvider.php
This PR allows devs to modify the default `wink` route prefix to anything they wish via the `wink.route_prefix` config variable.
For example, you could access the Wink admin panel at `/admin/` instead of the default `/wink/`.
=> Make Wink route prefix configurable

src/Http/routes.php
Previously almost all the wink routes were simply assigned `wink.` as a route name.
This change assigns all the routes to explicitly defined names.
=> Name all the Wink routes

public/app.js, public/mix-manifest.json, resources/js/components/ImagePicker.vue, resources/js/screens/team/edit.vue
Currently, image uploading not working in Firefox due to not passing "event" parameter to the handlers. Chrome and WebKit follows IE's old behavior of using a global symbol for "event" so it works without passing "event" parameter.
This commit fix image uploading for Firefox.
=> Fix ImagePicker bug in Firefox

src/Http/Controllers/ImageUploadsController.php
Currently, image uploading only works with the `local` driver. Using the url() method allows to use image upload with any driver, such as S3.
=> Image upload with any filesystem

public/app.js, public/light.css, public/mix-manifest.json, resources/js/screens/pages/edit.vue, resources/js/screens/posts/edit.vue, resources/js/screens/tags/edit.vue, resources/js/screens/team/edit.vue, src/Http/Controllers/PagesController.php, src/Http/Controllers/TagsController.php, src/Http/Controllers/TeamController.php, src/WinkAuthor.php, src/WinkPage.php, src/WinkTag.php
Following on from https://github.com/writingink/wink/pull/28#issuecomment-438559659, the SEO social/meta inputs have been added to pages, authors and tags.
Each of these are now consistent with the posts page, in that:
* a settings icon appears in the nav bar, which leads to a sub-panel menu
* the sub-panel has a link to the "SEO & Social" panel, and links to general settings if such a modal already existed (pages)
* the delete option is in the settings money, again to remain consistent with the post detail screen
=> Add seo modal to all sections

public/app.js, public/mix-manifest.json, resources/js/components/PageHeader.vue
This PR Add convert the Wink Logo to be a link which is the expected behavior to make it easier to navigate to the Home screen (which is the Posts screen) with a single click (instead of open the Dropdown and click Posts link).
=> Add link to Wink logo to goto the Home route

public/mix-manifest.json, resources/js/app.js
Just a minor change but it seemed to be that to be consistent with directive registration we could clean a bit the component registration by removing the `.vue` extension since it is not necessary.
=> Remove .vue extension from component registration

public/app.js, public/mix-manifest.json, resources/js/screens/posts/index.vue
Make border of Select lists in Filters Dropdown rounded for Firefox to be consistent with Chrome:
=> Fix style of Select lists in Filters Dropdown for Firefox

readme.md
In this PR, I updated the docs to remind the user to link their storage directory. I ran into this issue when messing around with Wink and noticed my images weren't uploading correctly. Once I linked the storage directories and made the proper directories, everything worked great!
=> On new installs, remind the user to link storage directories.

config/wink.php, src/WinkServiceProvider.php
I add this config option to change the middleware group.
I found it useful if I don't need the sessions / cookies on my website except for the wink admin part. On this way I can create a new middleware group and use that for wink.
=> Add the option to change the middleware group.

src/Console/MigrateCommand.php
Use Str::random and not str_random in the MigrateCommand
This is the only thing I found that doesn't work with Laravel 6.
=> Use the Str class and not the str_random helper

src/Http/Controllers/PostsController.php
I have built my blog using wink, and while using it I encountered the following problem.
My blog content is in arabic so for both posts and tags I used arabic names, but for slugs I used english.
First I Added this new tag
Then I added a post and I wanted to attach the **tutorials** tag to it, but instead of attaching the existing tag it creates a new one.
This is because the current code converts the tag name to slug and search if there is a tag slug with this same slug, but in my case it can`t because the slug is diffrent from the name so it creates a new tag, like the following
So in this PR I suggest instead of searching by the name slug, we search by id of the tag if it exists.
I know that Multi-lingual content is still in the future ideas which you are still not sure about, but I …
=> fix syncing existing tags to a post

src/Http/Resources/PagesResource.php, src/Http/Resources/PostsResource.php, src/Http/Resources/TagsResource.php, src/Http/Resources/TeamResource.php
This PR fixes #161 and #132. 
I would consider this issue to be an edge case since not a lot of people have reported having this issue.
If you had `Resource::withoutWrapping();` set in your `AppServiceProvider` boot method (like I had), then this package would not work ... (in my case I could not create posts) because all API endpoint would return without being wrapped in `data`. And then, Vue.js could not get the correct author_id in my case.
This PR forces data wrapping on resources by adding this line:
```
self::$wrap = 'data';
```
inside the resource `toArray` method.
This solution ignores the global `Resource::withoutWrapping();` which sets `$wrap` to `null`.
This PR does not break any functionality and is completely backward compatible. No user action required.
=> Forces data wrapping on resources

readme.md
It would be helpful to mention how to upload images with cache-control header.
Also, it's very common to use CDN like CloudFront in conjunction with S3.
It's not mentioned in Laravel official docs and so I googled how to achieve it.
https://laravel.com/docs/6.x/filesystem
=> Add documentation about uploading images to S3

readme.md
The `laravel/ui` package is required when installing Wink in a Laravel 7 project. Otherwise, a `Trait 'Illuminate\Foundation\Auth\AuthenticatesUsers' not found` exception occurs.
=> Add note regarding installation requirement

src/Console/MigrateCommand.php
Fixing issue #250 
I have faced the same issue as mentioned and found that you have just recently moved the repo under themsaid but the migrations still try to run from the old repo "writingink"
=> Change vendor name from writingink to themsaid in migration command

src/Http/Controllers/TeamController.php
Because the team endpoint does not using pagination. the JS load entities throws an exception `data.links` object is not defined
applying pagination 30 like in posts should solve the problem
=> Fix Team missing pagination

composer.json
While pulling the project and running a composer install for another PR I found out that the required larastan version conflicts with the Laravel version.
Because I didn't found any place where it is used I think it is a good idea to remove it. Else the version need to be changed.
=> Remove larastan because the version conflicts with the Laravel version

resources/js/components/MarkdownEditor.vue
This PR adds very simple image uploading ability to the Wink markdown editor. 
The functionality is mean to mimic the github markdown editor as seen in the gif below.
This also lets you insert (paste) the image at your cursor position.
I'm using bananas for scale to illustrate the functionality.
=> Add image pasting functionality to markdown editor

composer.json, src/Http/routes.php, src/WinkServiceProvider.php
This PR updates the `laravel/framework` dependency to work with either Laravel 7 or 8. 
The default route namespace has been removed from the `WinkServiceProvider`. All controller declarations have been updated to use the standard PHP callable syntax.
=> Laravel 8 Compatibility
